### ISSUE TITLE
언리얼 엔진을 설치하는 과정에서 발생한 문제 (패키지)

### ISSUE THREAD

**Issue by teoac** [edimoon777/DL_drone#3]
언리얼 엔진을 설치하는 과정에서 UnrealEngine.git을 복제하고 `~$ ./Setup.sh`를 수행하고 나면 아래와 같은 오류가 발생한다.

> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

> The following packages have unmet dependencies:
 clang-3.8 : Depends: libclang1-3.8 (= 1:3.8-2ubuntu1) but it is not going to be installed
             Depends: libobjc-5-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages."

**Comment by teoac** [comment]
'System Settings >> Software & Updates' 메뉴에서 'Updates' 탭에 'Recommned updates(xenial-updates)'를 선택해제 했었는데, 이로 인해 패키지 설치에 문제가 발생했었음. 이를 다시 선택해주니 패키지를 잘 설치하면서 `./Setup.sh` 설치 과정은 순탄하게 진행됨.

**Comment by OhMandarine** [comment]
Thank you very much, it works
